# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

pool:
  vmImage: 'Ubuntu 16.04'

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'
- script: java -jar "c:\Playtika Jar\whitesource-fs-agent-18.4.2.jar" -c "c:\Playtika Jar\whitesource-fs-agent.config" -d "c:\Playtika Jar"
  displayName: 'run FSA'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
